///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String commonBackIcon = 'assets/images/common/back_icon.png';
  static const String commonBackIconW = 'assets/images/common/back_icon_w.png';
  static const String commonRightArrow = 'assets/images/common/right_arrow.png';
  static const String commonRightDown = 'assets/images/common/right_down.png';
  static const String homeMine = 'assets/images/home/mine.png';
  static const String homeSearchHead = 'assets/images/home/search_head.png';
  static const String homeSearchIcon = 'assets/images/home/search_icon.png';
}
